[project]
name = "statcan"
version = "0.1.0"
description = "A StatCAN data wrangler."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "httpx>=0.27.2",
]

[project.optional-dependencies]
cache = [
    "requests-cache>=1.2.1",
]

